export default {
  CREATE_FOLDER_REQUEST_SUCCESS: 'CREATE_FOLDER_REQUEST_SUCCESS',
  FETCH_FOLDER_REQUEST: 'FETCH_FOLDER_REQUEST',
  FETCH_FOLDER_REQUEST_FAILURE: 'FETCH_FOLDER_REQUEST_FAILURE',
  FETCH_FOLDER_REQUEST_SUCCESS: 'FETCH_FOLDER_REQUEST_SUCCESS',
  LOG_IN_USER_SUCCESS: 'LOG_IN_USER_SUCCESS',
  LOG_OUT_USER: 'LOG_OUT_USER',
  SIGN_UP_USER_SUCCESS: 'SIGN_UP_USER_SUCCESS',
}
